trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformCloudToken: $(terraformCloudToken)

steps:
  - checkout: self

  - script: |
      python -m pip install --upgrade pip
      pip install terraform
      terraform -version
    displayName: 'Install Terraform'

  - script: |
      echo "Token: $TERRAFORM_CLOUD_TOKEN"  # Print full token
      mkdir -p ~/.terraform.d
      echo "{\"credentials\":{\"app.terraform.io\":{\"token\":\"$TERRAFORM_CLOUD_TOKEN\"}}}" > ~/.terraform.d/credentials.tfrc.json
      cat ~/.terraform.d/credentials.tfrc.json  # Print credentials file for verification
      terraform init
    displayName: 'Terraform Init'
    env:
      TERRAFORM_CLOUD_TOKEN: $(terraformCloudToken)

  - script: |
      terraform plan -out=tfplan
    displayName: 'Terraform Plan'

  - script: |
      terraform apply -input=false tfplan
    displayName: 'Terraform Apply'
    env:
      ARM_CLIENT_ID: $(azureClientId)
      ARM_CLIENT_SECRET: $(azureClientSecret)
      ARM_SUBSCRIPTION_ID: $(azureSubscriptionId)
      ARM_TENANT_ID: $(azureTenantId)
