location             = "southindia"
resource_group_name  = "INVIkRGP"
subnet_id            = "/subscriptions/e2ea6760-e0a3-428c-a8a0-9cf97fd3ff16/resourceGroups/INVIkRGP/providers/Microsoft.Network/virtualNetworks/indvikvm-vnet/subnets/subnet1"
vm_admin_username    = "viksur"
vm_admin_password    = "Azuresupport@123"
